Aprendizado baseado em instância ou KNN

```{r}
#install.packages("class")
library(class)
```

Iris
```{r}
head(iris)
summary(iris)
```

Dividimos em treino e classificação

```{r}
amostra = sample(2,150,replace = T,prob = c(0.7,0.3))
iristreino = iris[amostra==1,]
iristeste = iris[amostra==2,]
```

Visualizando as dimensões
```{r}
dim(iristreino)
dim(iristeste)
```

Fazemos a classificação sem criar modelo
Dados de treino (instâncias), dados de teste, classe real, número de vizinhos considerados

```{r}
# knn (referência, registro de referência, classe considerada )

# referência -> dados onde vai ser buscada a proximidade
# registro de referência -> dados que serão comparados com a referência p/ achar valores próximos
# classe considerada -> Classe que será buscada
# k -> quantidade de vizinhos mais próximos que será buscada a similaridade 

previsao = knn(iristreino[,1:4], iristeste[,1:4], iristreino[,5], k = 3)
previsao
# em vez de criarmos modelo, buscamos uma proximidade em tempo real
```

Matriz de confusão

```{r}

tabela = table(iristeste[,5], previsao)
tabela
```

Performance:

```{r}
(tabela[1] + tabela[5] + tabela[9]) / sum(tabela)
```

