Associadores com Apriori
MINERAÇÃO DE REGRAS DE ASSOCIAÇÃO

```{r}
install.packages("arules")
install.packages("arulesViz")
library(arules)
library(arulesViz)
```

Importa as transações

```{r}
# ******MUITO IMPORTANTE******
# método próprio para leitura de mercadorias
# basket -> formato de cesta
getwd()
trans = read.transactions("transacoes.txt", format = "basket", sep = ",")
trans
# inspeciona os itens
inspect(trans)
image(trans)
```
Mineração

```{r}
# suporte (N de transações / elementos), confiança (N trans com A / N trans com A e B ), coverage, lift (confiança / suporte)
# parametros = (suporte mínimo, confiança mínima, tamanho mínimo da regra)
regras = apriori(trans, parameter = list(supp = 0.5, conf = 0.5, minlen = 2))
regras # set of 4 rules
summary(regras)
inspect(regras)
```
Visualização

```{r}
plot(regras, method = "graph", control = list(type="items"))
plot(regras, method = "matrix", control = list(type="items"))
plot(regras, method = "matrix3D")
```

Salvar regras em disco
```{r}
write.csv(DATAFRAME(regras), "regras.csv")
```

