Multilayer Perceptron (neurônio mais simples)

RNA

```{r}
install.packages("neuralnet")
install.packages("mltool")
install.packages("data.table")
install.packages("caret", dependencies = T)
library(neuralnet)
library(mltools)
library(data.table)
library(caret)
```

Dimensionamento de Características - Padronização

```{r}
iris[,1:4]
# escalamento das instâncias
iris2 = scale(iris[,1:4])
# transformar em data frame novamente
iris2 = as.data.frame(iris2)
# Adiciona a classe do DB original
iris2$Species = iris$Species
iris2
```

Divisão treino e teste, usando método do pacote caret

```{r}
set.seed(1234)
# createDataPartition(1 até 150 (linhas do iris[1]))
# p = probabilidade (tamanho da amostra)
particao = createDataPartition(1:dim(iris2)[1], p = .7)
particao
# É criada uma coluna de Resample1 dentro de particao
# Variável de treino a partir da particao
iristreino = iris2[particao$Resample1,] # seleciona 70% automaticamente
# Variável de teste (negativa pois seleciona o resto do conjunto de dados, 30% automaticamente )
iristeste = iris2[- particao$Resample1,]
dim(iristreino) # 106 registros para treino
dim(iristeste) # 44 registros para treino
```

One Hot encoding para a classe

```{r}
iristreino = cbind(iristreino[,1:4], one_hot(as.data.table(iristreino[,5])))
iristreino
```

Criação do Modelo

```{r}
# Variaveis dependentes ~ variaveis independentes
modelo = neuralnet(V1_setosa + V1_versicolor + V1_virginica ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width, iristreino, 
                   hidden = c(5,4))
print(modelo)
plot(modelo)
```

Previsão

```{r}
# compute(modelo, dados de teste), não precisa passar a classe
teste = compute(modelo, iristeste[,1:4]) # output em pesos para cada uma das classes possíveis
teste$net.result
resultado = as.data.frame(teste$net.result)
resultado # retorna um dataframe sem nome e classes atribuídas, somente pesos distribuídos em colunas

```

Atribuimos nomes às colunas conforme a classe

```{r}
names(resultado)[1] = 'setosa'
names(resultado)[2] = 'versicolor'
names(resultado)[3] = 'virginica'
resultado
```

Usamos os nomes das colunas para preencher uma coluna com classe

```{r}
# colnames()
# resultado -> recebe os valores das 3 colunas
# max.col -> busca os maiores valores entre as colunas 1 a 3
# ties.method -> atribui o nome da coluna ao valor mais alto encontrado
resultado$class = colnames(resultado[,1:3])[max.col(resultado[,1:3], ties.method = 'first')]
resultado
```

Avaliação Performance
```{r}
confusao = table(resultado$class, iristeste$Species)
confusao
sum(diag(confusao) * 100 / sum(confusao))
```







